root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main.exe ./cmd/api"
  entrypoint = "./tmp/main.exe"
  delay = 500
  exclude_dir = ["tmp", "vendor"]
  include_ext = ["go"]
  kill_delay = "2s"
  rerun = false
  send_interrupt = true

[log]
  main_only = true
  time = false

[misc]
  clean_on_exit = true

[screen]
  clear_on_rebuild = false
