package mock

import (
	"context"

	"github.com/leonj/rep-set-lab/internal/ai"
)

// AIProvider is a handwritten mock for ai.Provider.
// Set func fields in tests; unset fields return sensible defaults.
type AIProvider struct {
	NameFunc            func() string
	GenerateWorkoutFunc func(ctx context.Context, req ai.WorkoutRequest) (ai.WorkoutResponse, ai.Usage, error)
}

func (m *AIProvider) Name() string {
	if m.NameFunc != nil {
		return m.NameFunc()
	}
	return "mock"
}

func (m *AIProvider) GenerateWorkout(ctx context.Context, req ai.WorkoutRequest) (ai.WorkoutResponse, ai.Usage, error) {
	if m.GenerateWorkoutFunc != nil {
		return m.GenerateWorkoutFunc(ctx, req)
	}
	return ai.WorkoutResponse{
		Title:       "Mock Workout",
		Description: "Generated by mock provider",
		WarmUp:      []ai.Exercise{{Name: "Light Jog", DurationSeconds: 300}},
		Main:        []ai.Exercise{{Name: "Mock Exercise", Sets: 3, Reps: 10}},
		CoolDown:    []ai.Exercise{{Name: "Stretch", DurationSeconds: 120}},
		Tips:        []string{"Stay hydrated"},
	}, ai.Usage{InputTokens: 100, OutputTokens: 200, CostUSD: 0.0004}, nil
}
